package-lock.json
package.json

Revert "Bump @vue/cli-service from 3.8.4 to 3.9.2"

---

package-lock.json
package.json

Revert "Bump core-js from 2.6.9 to 3.1.4"

---

package-lock.json
package.json

Revert "Bump eslint-plugin-vue from 5.2.2 to 5.2.3"

---

package-lock.json
package.json

Revert "Bump @vue/cli-plugin-babel from 3.8.0 to 3.9.0"

---

package-lock.json
package.json

Revert "Bump vue-router from 3.0.6 to 3.0.7"

---

src/pages/Home.vue

I will make more pull requests for other staff members. Asking them for their presence request and if people wanna change it.

♻️ Add Alanexei Example

---

src/pages/errors/Maintenance.vue
src/stylesheets/components/visibility.less

:sparkles: Updated.

---

src/pages/store/Userpage.vue
src/stylesheets/components/container.less

Don't forget to merge master with stable :)

:sparkles: Added badges.

---

src/components/StoreCard.vue
src/views/store/PresencePage.vue

Somebody had to do this. Sorry Vok, and thanks for making me to use Vue/Nuxt for the first time in my life. _MODULE INSTALLATION TOOK FOREVER_
~~pls accept~~

Escape Imgur images.

---

src/components/StoreCard.vue
src/views/store/PresencePage.vue

Thanks to Tim, and me ofc. And thanks to Vok, this worth to try.

Unescape Imgur since API does that now!

---

nuxt.config.js
src/components/StoreCard.vue
src/views/Contributors.vue
src/views/Store.vue
src/views/store/PresencePage.vue
src/views/users/Userpage.vue

sum uri componet.
sum improv
sum margin
vala 🎉

Smol fixes for hot linking and non presence developer pages

---

src/views/users/Userpage.vue

updat and chang a stirg.

---

src/stylesheets/components/body.scss
src/views/Homepage.vue
src/views/Store.vue

Yes, it looks good now. Still missing lots of strings on Crowdin. bad bad tim

Fixes for language stuff.

---

src/components/CreditCard.vue
src/views/Store.vue
src/views/errors/NotFound.vue
src/views/users/Userpage.vue

Everything with translations!

---

nuxt.config.js

Have to disable this option until we get CDN working.

---

src/components/CreditCard.vue
src/layouts/error.vue
src/stylesheets/components/body.scss
src/views/Contributors.vue
src/views/Homepage.vue
src/views/store/PresencePage.vue
src/views/users/Userpage.vue

Added new strings and fixed some of the existed ones, contributions are now also on user profiles etc.
[Click to see a broken GIF of contributions on user pages](https://cdn.discordapp.com/attachments/518468138023649289/674997858839298048/2020-02-06_18-18-40.gif).

Contributions section in profiles, improvements, fixes.

---

src/components/StoreCard.vue
src/views/store/PresencePage.vue

Single URL presences fix & link support in description!

---

nuxt.config.js
src/views/Homepage.vue
src/views/store/PresencePage.vue

It's now automated! Oh and basically it doesn't throw error when error returns "User not found." from the API.

Version on the homepage fix

---

src/views/Partners.vue

🔞NSFW Content removed

---

src/views/users/Userpage.vue

end of the "glasses" era

---

src/components/Checkbox.vue
src/components/Sponsor.vue
src/components/StoreCard.vue
src/stylesheets/components/card.scss
src/stylesheets/components/container.scss
src/stylesheets/components/footer.scss
src/stylesheets/components/grid.scss
src/stylesheets/components/switcher.scss
src/views/Contributors.vue
src/views/Downloads.vue
src/views/Partners.vue
src/views/Store.vue
src/views/store/PresencePage.vue

More fixes and more mobile related stuff.

---

src/stylesheets/components/container.scss
src/views/Partners.vue

Actual "random images"!

---

src/components/CreditCard.vue
src/stylesheets/components/container.scss
src/views/Downloads.vue

~~prevent future confusion? scams? idk. just wanted to add it~~

most useless changes ever.

---

src/layouts/default.vue
src/stylesheets/components/grid.scss
src/views/Store.vue
src/views/store/PresencePage.vue

Now you're able to use `q`, `query` or `search` as a URL parameter (was suggested in #104) to quickly search through presences around... Click [here](https://beta.premid.app/store?q=eggsy) for example when this PR is merged.
Also, there are now search filters such as `tag` and `author` which you can basically filter them. Not like Discord's but I've tried to clone that, I think it's pretty good like this. You can also use Discord IDs if you're searching with `author` filter. Neat? [Follow](https://twitter.com/eggsywashere).

Tag/author filtered searching. Query support.

---

nuxt.config.js
src/components/StoreCard.vue
src/components/mixins/Detection.js
src/store/presences.js
src/stylesheets/components/card.scss
src/views/Downloads.vue
src/views/Store.vue
src/views/store/PresencePage.vue

- Twitter tags [WIP]
- Presence liking system (basic, no auth, stored in browser).
- Partner badges on presence profiles and presence cards.
- Clicking on a tag on a presence badge now redirects you to store with `tag:` query.

Twitter tags, presence liking system, partner badges and more!

---

src/stylesheets/components/card.scss
src/views/store/PresencePage.vue

Important fix for partner presences!

---

src/components/StoreCard.vue
src/store/presences.js
src/views/store/PresencePage.vue

Oof. How does it even work for others!

Small but IMPORTANT fix to presence liking system.

---

src/pages/store/presences/_presenceName.vue
src/stylesheets/components/container.scss

Removed add/remove button on store for presences with button: false

---

src/components/JoinGuild.vue
src/pages/jobs.vue
src/stylesheets/components/container.scss

Using same modal format as applications but with smaller size.
Task: #46m3gm

Check if member already joined PreMiD guild on apply

---

src/components/Footer.vue
src/pages/downloads.vue
src/pages/index.vue
src/pages/jobs.vue
src/stylesheets/components/card.scss

:fire: Fixed user cards, Instagram, modal fix!

---

src/components/Footer.vue
src/components/mixins/Detection.js
src/layouts/skipAds.vue
src/pages/downloads.vue
src/stylesheets/components/card.scss

:fire: Better ads wrapper, full mobile support (ads).

---

src/pages/store/presences/_presenceName.vue

Changed presences source url to comply with the [new presences repo structure](https://github.com/PreMiD/Presences/pull/1524).

Updated presence source url to work with the new presences repo scheme

---

nuxt.config.js
package.json
src/components/Apply.vue
src/components/CreditCard.vue
src/components/JobApply.vue
src/components/LanguageNotification.vue
src/components/Navigation.vue
src/components/StoreCard.vue
src/components/mixins/Detection.js
src/components/mixins/Presence.js
src/components/staff/PullRequests.vue
src/components/staff/StaffActivity.vue
src/components/staff/Ticket.vue
src/layouts/default.vue
src/layouts/error.vue
src/layouts/skipAds.vue
src/pages/beta/index.vue
src/pages/beta/register.vue
src/pages/bug.vue
src/pages/callback.vue
src/pages/downloads.vue
src/pages/index.vue
src/pages/login.vue
src/pages/logout.vue
src/pages/partners.vue
src/pages/staff.vue
src/pages/store/index.vue
src/pages/store/presences/_presenceName.vue
src/pages/users/_userId.vue
yarn.lock

fixed downloads and more stuff

:bug: fix, :fire: store and presence page is now on graphql api (v3)

---

src/pages/bug.vue
src/pages/partners.vue

https://github.com/PreMiD/API/pull/192

Bug Report Fixed

---

src/pages/store/presences/_presenceName.vue

fix bug of image format

---

README.md

Updated to the static premid domain redirect

Discord Invite Link

---

src/components/AdsModal.vue

it was displaying "thank you" when user's adblock was enabled 🤣

🐛 some fixes

---

cryptify.js
src/layouts/skipAds.vue

Using requestAnimationFrame instead of setInterval :)

🐛 Workaround for timer?

---

.github/workflows/deploy.yml

This will deploy the website at 5am UTC every day, updating translations.

Schedule the action to run every day at 5am UTC

---

src/components/StoreCard.vue
src/pages/store/presences/_presenceName.vue

Store pages, Presence page and User Profile all load the thumbnail image faster about half the time required or faster.
Not used on the icons due to Imgur doing weird AA on smaller and larger icons.

Optimsed thumbnails | Loads imgur images faster

---

src/pages/store/presences/_presenceName.vue
src/pages/users/_userId.vue

No Profile fix, manally from master/beta

---

src/components/mixins/Detection.js

Revert "🐛 "

---

src/layouts/skipAds.vue

Because for now it's not in store 😞

:bug: Change Edge url to chrome webstore

---

src/layouts/skipAds.vue

Revert ":bug: Change Edge url to chrome webstore"

---

src/components/Footer.vue

This PR simply adds the year in which PreMiD was created to the footer

feat(Footer): add starting year to copyright

---

package.json
yarn.lock

Revert "🔼 Bump sass-loader from 12.3.0 to 12.4.0"

---

src/pages/contributors.vue

Title (yes this was tested, yes it works)
Before: 
After:

refactor(contributors): sort users alphabetically

---

src/pages/store/presences/_presenceName.vue

Localization pr: https://github.com/PreMiD/Localization/pull/7070
https://github.com/PreMiD/Website/pull/873/commits/8d496485e23fc57caa8fe2a72420068cb682af59: <img src="https://homiesexu.al/aVUxTb7AMG.gif?key=hLkpSRdk1ke5O4">

Add RegExp information

---

src/stylesheets/components/body.scss

Fix tooltip on user page

---

src/components/CreditCard.vue
src/pages/contributors.vue

- Adds Presence Developers back
- Sorts Translators and Proofreaders

feat(/contributors): page update

---

src/pages/index.vue
src/pages/users/_userId.vue
src/stylesheets/components/card.scss
src/stylesheets/components/container.scss

fix: no mobile logo squash

---

nuxt.config.js

fix: GET RID OF LOADER FFS
